# Generated by Django 5.2.15 on 2026-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.CharField(
                        help_text="E.164 format, e.g. +12223334444",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("PROVIDER", "Provider"),
                            ("MEDICAL_ASSISTANT", "Medical Assistant"),
                            ("FRONT_DESK", "Front Desk"),
                            ("MANAGEMENT", "Management"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
