# Generated by Django 5.2.15 on 2026-07-17 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SHIFT_ASSIGNED", "Shift Assigned"),
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_REJECTED", "Leave Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message_body", models.TextField()),
                (
                    "related_object_id",
                    models.IntegerField(
                        blank=True, help_text="ID of related Shift or Leave", null=True
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_send_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this notification should be sent (for batching)",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_queue",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_sent", "created_at"],
                        name="messaging_n_employe_28e405_idx",
                    )
                ],
            },
        ),
    ]
