# Generated by Django 5.2.15 on 2026-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_alter_notificationqueue_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationqueue",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("SHIFT_ASSIGNED", "Shift Assigned"),
                    ("SHIFT_CANCELLED", "Shift Cancelled"),
                    ("SHIFT_UPDATED", "Shift Updated"),
                    ("LEAVE_APPROVED", "Leave Approved"),
                    ("LEAVE_REJECTED", "Leave Rejected"),
                    ("LEAVE_CANCELLED", "Leave Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
