# Generated by Django 5.2.15 on 2026-07-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_notificationqueue_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_assignment_enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
