# Generated by Django 5.2.15 on 2026-07-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_notificationsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="e.g. Office Manager", max_length=120
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email only"),
                            ("SMS", "SMS only"),
                            ("BOTH", "Email and SMS"),
                        ],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="leave_alerts_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
