# Generated by Django 5.2.15 on 2026-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_notificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="leave_email_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="leave_email_recipients",
            field=models.TextField(
                blank=True, help_text="Admin emails, one per line or comma-separated."
            ),
        ),
    ]
