# Generated by Django 5.2.15 on 2026-07-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_admincontact_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationsetting",
            old_name="shift_assignment_enabled",
            new_name="shift_sms_enabled",
        ),
    ]
