# Generated by Django 5.2.15 on 2026-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shift",
            name="needs_attention",
            field=models.BooleanField(default=False),
        ),
    ]
