# Generated by Django 5.2.15 on 2026-07-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("shifts", "0002_shift_confirmed_shift_needs_attention"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="locations.location",
            ),
        ),
    ]
